apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
  namespace: bookstore
data:
  MONGO_DB: "BOOKSTORE"
  MONGO_COLLECTION: "books"
  MONGO_HOST: "mongo-service"
  MONGO_PORT: "27017"

